Holiday: Normalize holiday data and query to handle 'day'
duckduckgo/zeroclickinfo-spice pull request #3550
Opened 2018-10-06 02:44 UTC by machineloop

## Description of new Instant Answer, or changes
The query "when is thanksgiving" doesn't trigger this IA because the list of Holidays for "Canada" and "USA" (canada.txt, us.txt) have the name of the holiday as "thanksgiving day", so a check for "thanksgiving" does not match.

This PR removes "day" from all holidays, and strips it from the query when present to allow it to match the normalized data.

## Related Issues and Discussions
Fixes #3448 

## People to notify
CC: @sekhavati @moollaza 

---

IA Page: http://duck.co/ia/view/holiday
Maintainer: @sekhavati

2018-10-06 03:00 UTC, daxtheduck commented
## [Holiday](https://duck.co/ia/view/holiday)

**Description**: Gives the next occurrence of the specified holiday. If a year is specified, it will give the event date for the given year.

**Example Query**: [when is halloween](https://beta.duckduckgo.com/?q=when%20is%20halloween), [when is christmas day in the uk](https://beta.duckduckgo.com/?q=when%20is%20christmas%20day%20in%20the%20uk), [when is memorial day 2018](https://beta.duckduckgo.com/?q=when%20is%20memorial%20day%202018)

**Tab Name**: Answer

**Source**: timeanddate.com

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/holiday)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/holiday)*

2018-11-13 15:41 UTC, moollaza requested changes
@machineloop this is looking pretty good.

Can you update the tests to show that the expected behaviour now works. i.e. the query "thanksgiving" with a location of Canada or USA, should return the appropriate result.

2018-11-13 15:41 UTC, moollaza commented on lib/DDG/Spice/Holiday.pm
> +    $query =~ s/[[:space:]]day$//;
I would suggest a minor simplification:
```suggestion
    $query =~ s/\sday$//;
```

2018-11-13 15:41 UTC, moollaza commented on share/spice/holiday/sanitize-holidays.sh
> +    sed -i 's/[[:space:]]day$//' $country
I guess we can stick with `[[:space:]]` here as well for consistency, though `\s` should suffice.

2018-11-13 15:44 UTC, moollaza commented
@machineloop apologies for the delay on reviewing. If it's not already there, can you also update the shell script to deduplicate the files?

Thanks!

2022-10-14 17:14 UTC, closed without merging